const {createRequire}=require('node:module');const path=require('node:path');
const requireQA=process.env.PLAYWRIGHT_ROOT?createRequire(path.resolve(process.env.PLAYWRIGHT_ROOT,'package.json')):require;
const {chromium}=requireQA('playwright-core');
const fs=require('fs'),http=require('http');const root=path.resolve(__dirname,'../templates/starter'),out=path.resolve(__dirname,'screenshots');fs.mkdirSync(out,{recursive:true});const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url);fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(e?'missing':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/usr/local/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const errors=[];try{
for(const [w,h]of [[1440,900],[390,844]]){const p=await browser.newPage({viewport:{width:w,height:h}});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)errors.push(r.url());});await p.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});await p.waitForSelector('body.ready');await p.waitForFunction(()=>window.layeredWorld.inspect().progress>.015);const first=await p.evaluate(()=>window.layeredWorld.inspect());if(!first.playing||first.guideCount!==1||first.chapters.join(',')!=='opening,woodland,pond,ending')errors.push('initial state');await p.locator('#play').click();const still=await p.evaluate(()=>window.layeredWorld.inspect());await p.waitForTimeout(450);const moved=await p.evaluate(()=>window.layeredWorld.inspect());if(Math.abs(still.progress-moved.progress)>.003||moved.motionTime<=still.motionTime)errors.push('pause/autonomous motion');
await p.evaluate(()=>{const a=window.layeredWorld;a.elapsed=17*1.45;a.progress=1.45;scrollTo(0,a.progress*a.unit);});await p.waitForTimeout(300);const before=await p.evaluate(()=>window.layeredWorld.inspect());const initialFrame=before.meshes.find(m=>m.asset==='squirrel').frame;await p.waitForFunction(frame=>window.layeredWorld.inspect().meshes.find(m=>m.asset==='squirrel').frame!==frame,initialFrame,{timeout:2500});const after=await p.evaluate(()=>window.layeredWorld.inspect());await p.screenshot({path:path.join(out,`${w}-woodland.png`)});
await p.mouse.move(w*.55,h*.65);await p.mouse.down();await p.mouse.move(w*.55+50,h*.65-20,{steps:6});await p.mouse.up();await p.waitForTimeout(200);if((await p.evaluate(()=>window.layeredWorld.inspect())).pan.cx===0)errors.push('drag failed');await p.locator('#reset').click();await p.locator('#play').click();await p.waitForFunction(()=>window.layeredWorld.inspect().playing);await p.mouse.wheel(0,300);await p.waitForFunction(()=>!window.layeredWorld.inspect().playing);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))errors.push('overflow');await p.close();}
console.log(JSON.stringify({errors,screenshots:2}));if(errors.length)process.exitCode=1;
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
